// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tile.proto

/*
Package tile is a generated protocol buffer package.

It is generated from these files:
	tile.proto

It has these top-level messages:
	MarkedDeleted
	Tile
*/
package tile

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/united-drivers/valhalla/pb/segment"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *MarkedDeleted) Validate() error {
	return nil
}
func (this *Tile) Validate() error {
	for _, item := range this.Entries {
		if err := go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return go_proto_validators.FieldError("Entries", err)
		}
	}
	return nil
}
func (this *Tile_Entry) Validate() error {
	if this.Segment != nil {
		if err := go_proto_validators.CallValidatorIfExists(&(*(this.Segment))); err != nil {
			return go_proto_validators.FieldError("Segment", err)
		}
	}
	if this.Marker != nil {
		if err := go_proto_validators.CallValidatorIfExists(&(*(this.Marker))); err != nil {
			return go_proto_validators.FieldError("Marker", err)
		}
	}
	return nil
}
