// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fileformat.proto

/*
Package fileformat is a generated protocol buffer package.

It is generated from these files:
	fileformat.proto

It has these top-level messages:
	Blob
	BlobHeader
*/
package fileformat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Blob) Validate() error {
	return nil
}
func (this *BlobHeader) Validate() error {
	return nil
}
