// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: directions_options.proto

/*
Package valhalla_odin is a generated protocol buffer package.

It is generated from these files:
	directions_options.proto

It has these top-level messages:
	DirectionsOptions
*/
package valhalla_odin

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import valhalla_odin1 "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// LatLng from public import tripcommon.proto
type LatLng valhalla_odin1.LatLng

func (m *LatLng) Reset()          { (*valhalla_odin1.LatLng)(m).Reset() }
func (m *LatLng) String() string  { return (*valhalla_odin1.LatLng)(m).String() }
func (*LatLng) ProtoMessage()     {}
func (m *LatLng) GetLat() float32 { return (*valhalla_odin1.LatLng)(m).GetLat() }
func (m *LatLng) GetLng() float32 { return (*valhalla_odin1.LatLng)(m).GetLng() }

// BoundingBox from public import tripcommon.proto
type BoundingBox valhalla_odin1.BoundingBox

func (m *BoundingBox) Reset()         { (*valhalla_odin1.BoundingBox)(m).Reset() }
func (m *BoundingBox) String() string { return (*valhalla_odin1.BoundingBox)(m).String() }
func (*BoundingBox) ProtoMessage()    {}
func (m *BoundingBox) GetMinLl() *LatLng {
	return (*LatLng)((*valhalla_odin1.BoundingBox)(m).GetMinLl())
}
func (m *BoundingBox) GetMaxLl() *LatLng {
	return (*LatLng)((*valhalla_odin1.BoundingBox)(m).GetMaxLl())
}

// Location from public import tripcommon.proto
const Default_Location_Type = valhalla_odin1.Default_Location_Type
const Default_Location_HeadingTolerance = valhalla_odin1.Default_Location_HeadingTolerance
const Default_Location_NodeSnapTolerance = valhalla_odin1.Default_Location_NodeSnapTolerance
const Default_Location_MinimumReachability = valhalla_odin1.Default_Location_MinimumReachability
const Default_Location_Radius = valhalla_odin1.Default_Location_Radius
const Default_Location_Time = valhalla_odin1.Default_Location_Time
const Default_Location_RankCandidates = valhalla_odin1.Default_Location_RankCandidates

type Location valhalla_odin1.Location

func (m *Location) Reset()         { (*valhalla_odin1.Location)(m).Reset() }
func (m *Location) String() string { return (*valhalla_odin1.Location)(m).String() }
func (*Location) ProtoMessage()    {}
func (m *Location) GetLl() *LatLng { return (*LatLng)((*valhalla_odin1.Location)(m).GetLl()) }
func (m *Location) GetType() Location_Type {
	return (Location_Type)((*valhalla_odin1.Location)(m).GetType())
}
func (m *Location) GetHeading() uint32    { return (*valhalla_odin1.Location)(m).GetHeading() }
func (m *Location) GetName() string       { return (*valhalla_odin1.Location)(m).GetName() }
func (m *Location) GetStreet() string     { return (*valhalla_odin1.Location)(m).GetStreet() }
func (m *Location) GetCity() string       { return (*valhalla_odin1.Location)(m).GetCity() }
func (m *Location) GetState() string      { return (*valhalla_odin1.Location)(m).GetState() }
func (m *Location) GetPostalCode() string { return (*valhalla_odin1.Location)(m).GetPostalCode() }
func (m *Location) GetCountry() string    { return (*valhalla_odin1.Location)(m).GetCountry() }
func (m *Location) GetPhone() string      { return (*valhalla_odin1.Location)(m).GetPhone() }
func (m *Location) GetUrl() string        { return (*valhalla_odin1.Location)(m).GetUrl() }
func (m *Location) GetDateTime() string   { return (*valhalla_odin1.Location)(m).GetDateTime() }
func (m *Location) GetSideOfStreet() Location_SideOfStreet {
	return (Location_SideOfStreet)((*valhalla_odin1.Location)(m).GetSideOfStreet())
}
func (m *Location) GetHeadingTolerance() uint32 {
	return (*valhalla_odin1.Location)(m).GetHeadingTolerance()
}
func (m *Location) GetNodeSnapTolerance() uint32 {
	return (*valhalla_odin1.Location)(m).GetNodeSnapTolerance()
}
func (m *Location) GetWayId() uint64 { return (*valhalla_odin1.Location)(m).GetWayId() }
func (m *Location) GetMinimumReachability() uint32 {
	return (*valhalla_odin1.Location)(m).GetMinimumReachability()
}
func (m *Location) GetRadius() uint32       { return (*valhalla_odin1.Location)(m).GetRadius() }
func (m *Location) GetAccuracy() uint32     { return (*valhalla_odin1.Location)(m).GetAccuracy() }
func (m *Location) GetTime() float64        { return (*valhalla_odin1.Location)(m).GetTime() }
func (m *Location) GetRankCandidates() bool { return (*valhalla_odin1.Location)(m).GetRankCandidates() }
func (m *Location) GetPathEdges() []*Location_PathEdge {
	o := (*valhalla_odin1.Location)(m).GetPathEdges()
	if o == nil {
		return nil
	}
	s := make([]*Location_PathEdge, len(o))
	for i, x := range o {
		s[i] = (*Location_PathEdge)(x)
	}
	return s
}
func (m *Location) GetFilteredEdges() []*Location_PathEdge {
	o := (*valhalla_odin1.Location)(m).GetFilteredEdges()
	if o == nil {
		return nil
	}
	s := make([]*Location_PathEdge, len(o))
	for i, x := range o {
		s[i] = (*Location_PathEdge)(x)
	}
	return s
}
func (m *Location) GetOriginalIndex() uint32 { return (*valhalla_odin1.Location)(m).GetOriginalIndex() }
func (m *Location) GetProjectedLl() *LatLng {
	return (*LatLng)((*valhalla_odin1.Location)(m).GetProjectedLl())
}

// PathEdge from public import tripcommon.proto
type Location_PathEdge valhalla_odin1.Location_PathEdge

func (m *Location_PathEdge) Reset()         { (*valhalla_odin1.Location_PathEdge)(m).Reset() }
func (m *Location_PathEdge) String() string { return (*valhalla_odin1.Location_PathEdge)(m).String() }
func (*Location_PathEdge) ProtoMessage()    {}
func (m *Location_PathEdge) GetGraphId() uint64 {
	return (*valhalla_odin1.Location_PathEdge)(m).GetGraphId()
}
func (m *Location_PathEdge) GetPercentAlong() float32 {
	return (*valhalla_odin1.Location_PathEdge)(m).GetPercentAlong()
}
func (m *Location_PathEdge) GetLl() *LatLng {
	return (*LatLng)((*valhalla_odin1.Location_PathEdge)(m).GetLl())
}
func (m *Location_PathEdge) GetSideOfStreet() Location_SideOfStreet {
	return (Location_SideOfStreet)((*valhalla_odin1.Location_PathEdge)(m).GetSideOfStreet())
}
func (m *Location_PathEdge) GetDistance() float32 {
	return (*valhalla_odin1.Location_PathEdge)(m).GetDistance()
}
func (m *Location_PathEdge) GetMinimumReachability() int32 {
	return (*valhalla_odin1.Location_PathEdge)(m).GetMinimumReachability()
}
func (m *Location_PathEdge) GetBeginNode() bool {
	return (*valhalla_odin1.Location_PathEdge)(m).GetBeginNode()
}
func (m *Location_PathEdge) GetEndNode() bool {
	return (*valhalla_odin1.Location_PathEdge)(m).GetEndNode()
}
func (m *Location_PathEdge) GetNames() []string {
	return (*valhalla_odin1.Location_PathEdge)(m).GetNames()
}

// TransitEgressInfo from public import tripcommon.proto
type TransitEgressInfo valhalla_odin1.TransitEgressInfo

func (m *TransitEgressInfo) Reset()         { (*valhalla_odin1.TransitEgressInfo)(m).Reset() }
func (m *TransitEgressInfo) String() string { return (*valhalla_odin1.TransitEgressInfo)(m).String() }
func (*TransitEgressInfo) ProtoMessage()    {}
func (m *TransitEgressInfo) GetOnestopId() string {
	return (*valhalla_odin1.TransitEgressInfo)(m).GetOnestopId()
}
func (m *TransitEgressInfo) GetName() string { return (*valhalla_odin1.TransitEgressInfo)(m).GetName() }
func (m *TransitEgressInfo) GetLl() *LatLng {
	return (*LatLng)((*valhalla_odin1.TransitEgressInfo)(m).GetLl())
}

// TransitStationInfo from public import tripcommon.proto
type TransitStationInfo valhalla_odin1.TransitStationInfo

func (m *TransitStationInfo) Reset()         { (*valhalla_odin1.TransitStationInfo)(m).Reset() }
func (m *TransitStationInfo) String() string { return (*valhalla_odin1.TransitStationInfo)(m).String() }
func (*TransitStationInfo) ProtoMessage()    {}
func (m *TransitStationInfo) GetOnestopId() string {
	return (*valhalla_odin1.TransitStationInfo)(m).GetOnestopId()
}
func (m *TransitStationInfo) GetName() string {
	return (*valhalla_odin1.TransitStationInfo)(m).GetName()
}
func (m *TransitStationInfo) GetLl() *LatLng {
	return (*LatLng)((*valhalla_odin1.TransitStationInfo)(m).GetLl())
}

// TransitPlatformInfo from public import tripcommon.proto
type TransitPlatformInfo valhalla_odin1.TransitPlatformInfo

func (m *TransitPlatformInfo) Reset() { (*valhalla_odin1.TransitPlatformInfo)(m).Reset() }
func (m *TransitPlatformInfo) String() string {
	return (*valhalla_odin1.TransitPlatformInfo)(m).String()
}
func (*TransitPlatformInfo) ProtoMessage() {}
func (m *TransitPlatformInfo) GetType() TransitPlatformInfo_Type {
	return (TransitPlatformInfo_Type)((*valhalla_odin1.TransitPlatformInfo)(m).GetType())
}
func (m *TransitPlatformInfo) GetOnestopId() string {
	return (*valhalla_odin1.TransitPlatformInfo)(m).GetOnestopId()
}
func (m *TransitPlatformInfo) GetName() string {
	return (*valhalla_odin1.TransitPlatformInfo)(m).GetName()
}
func (m *TransitPlatformInfo) GetArrivalDateTime() string {
	return (*valhalla_odin1.TransitPlatformInfo)(m).GetArrivalDateTime()
}
func (m *TransitPlatformInfo) GetDepartureDateTime() string {
	return (*valhalla_odin1.TransitPlatformInfo)(m).GetDepartureDateTime()
}
func (m *TransitPlatformInfo) GetAssumedSchedule() bool {
	return (*valhalla_odin1.TransitPlatformInfo)(m).GetAssumedSchedule()
}
func (m *TransitPlatformInfo) GetLl() *LatLng {
	return (*LatLng)((*valhalla_odin1.TransitPlatformInfo)(m).GetLl())
}
func (m *TransitPlatformInfo) GetStationOnestopId() string {
	return (*valhalla_odin1.TransitPlatformInfo)(m).GetStationOnestopId()
}
func (m *TransitPlatformInfo) GetStationName() string {
	return (*valhalla_odin1.TransitPlatformInfo)(m).GetStationName()
}

// Type from public import tripcommon.proto
type Location_Type valhalla_odin1.Location_Type

var Location_Type_name = valhalla_odin1.Location_Type_name
var Location_Type_value = valhalla_odin1.Location_Type_value

func (x Location_Type) String() string { return (valhalla_odin1.Location_Type)(x).String() }
func (x Location_Type) Enum() *Location_Type {
	return (*Location_Type)((valhalla_odin1.Location_Type)(x).Enum())
}
func (x *Location_Type) UnmarshalJSON(data []byte) error {
	return (*valhalla_odin1.Location_Type)(x).UnmarshalJSON(data)
}

const Location_kBreak = Location_Type(valhalla_odin1.Location_kBreak)
const Location_kThrough = Location_Type(valhalla_odin1.Location_kThrough)

// SideOfStreet from public import tripcommon.proto
type Location_SideOfStreet valhalla_odin1.Location_SideOfStreet

var Location_SideOfStreet_name = valhalla_odin1.Location_SideOfStreet_name
var Location_SideOfStreet_value = valhalla_odin1.Location_SideOfStreet_value

func (x Location_SideOfStreet) String() string {
	return (valhalla_odin1.Location_SideOfStreet)(x).String()
}
func (x Location_SideOfStreet) Enum() *Location_SideOfStreet {
	return (*Location_SideOfStreet)((valhalla_odin1.Location_SideOfStreet)(x).Enum())
}
func (x *Location_SideOfStreet) UnmarshalJSON(data []byte) error {
	return (*valhalla_odin1.Location_SideOfStreet)(x).UnmarshalJSON(data)
}

const Location_kNone = Location_SideOfStreet(valhalla_odin1.Location_kNone)
const Location_kLeft = Location_SideOfStreet(valhalla_odin1.Location_kLeft)
const Location_kRight = Location_SideOfStreet(valhalla_odin1.Location_kRight)

// Type from public import tripcommon.proto
type TransitPlatformInfo_Type valhalla_odin1.TransitPlatformInfo_Type

var TransitPlatformInfo_Type_name = valhalla_odin1.TransitPlatformInfo_Type_name
var TransitPlatformInfo_Type_value = valhalla_odin1.TransitPlatformInfo_Type_value

func (x TransitPlatformInfo_Type) String() string {
	return (valhalla_odin1.TransitPlatformInfo_Type)(x).String()
}
func (x TransitPlatformInfo_Type) Enum() *TransitPlatformInfo_Type {
	return (*TransitPlatformInfo_Type)((valhalla_odin1.TransitPlatformInfo_Type)(x).Enum())
}
func (x *TransitPlatformInfo_Type) UnmarshalJSON(data []byte) error {
	return (*valhalla_odin1.TransitPlatformInfo_Type)(x).UnmarshalJSON(data)
}

const TransitPlatformInfo_kStop = TransitPlatformInfo_Type(valhalla_odin1.TransitPlatformInfo_kStop)
const TransitPlatformInfo_kStation = TransitPlatformInfo_Type(valhalla_odin1.TransitPlatformInfo_kStation)

type DirectionsOptions_Units int32

const (
	DirectionsOptions_kilometers DirectionsOptions_Units = 0
	DirectionsOptions_miles      DirectionsOptions_Units = 1
)

var DirectionsOptions_Units_name = map[int32]string{
	0: "kilometers",
	1: "miles",
}
var DirectionsOptions_Units_value = map[string]int32{
	"kilometers": 0,
	"miles":      1,
}

func (x DirectionsOptions_Units) Enum() *DirectionsOptions_Units {
	p := new(DirectionsOptions_Units)
	*p = x
	return p
}
func (x DirectionsOptions_Units) String() string {
	return proto.EnumName(DirectionsOptions_Units_name, int32(x))
}
func (x *DirectionsOptions_Units) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DirectionsOptions_Units_value, data, "DirectionsOptions_Units")
	if err != nil {
		return err
	}
	*x = DirectionsOptions_Units(value)
	return nil
}
func (DirectionsOptions_Units) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDirectionsOptions, []int{0, 0}
}

type DirectionsOptions_Format int32

const (
	DirectionsOptions_json DirectionsOptions_Format = 0
	DirectionsOptions_gpx  DirectionsOptions_Format = 1
	DirectionsOptions_osrm DirectionsOptions_Format = 2
)

var DirectionsOptions_Format_name = map[int32]string{
	0: "json",
	1: "gpx",
	2: "osrm",
}
var DirectionsOptions_Format_value = map[string]int32{
	"json": 0,
	"gpx":  1,
	"osrm": 2,
}

func (x DirectionsOptions_Format) Enum() *DirectionsOptions_Format {
	p := new(DirectionsOptions_Format)
	*p = x
	return p
}
func (x DirectionsOptions_Format) String() string {
	return proto.EnumName(DirectionsOptions_Format_name, int32(x))
}
func (x *DirectionsOptions_Format) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DirectionsOptions_Format_value, data, "DirectionsOptions_Format")
	if err != nil {
		return err
	}
	*x = DirectionsOptions_Format(value)
	return nil
}
func (DirectionsOptions_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDirectionsOptions, []int{0, 1}
}

type DirectionsOptions_Action int32

const (
	DirectionsOptions_route              DirectionsOptions_Action = 1
	DirectionsOptions_locate             DirectionsOptions_Action = 2
	DirectionsOptions_sources_to_targets DirectionsOptions_Action = 6
	DirectionsOptions_optimized_route    DirectionsOptions_Action = 7
	DirectionsOptions_isochrone          DirectionsOptions_Action = 8
	DirectionsOptions_trace_route        DirectionsOptions_Action = 9
	DirectionsOptions_trace_attributes   DirectionsOptions_Action = 10
	DirectionsOptions_height             DirectionsOptions_Action = 11
	DirectionsOptions_transit_available  DirectionsOptions_Action = 12
)

var DirectionsOptions_Action_name = map[int32]string{
	1:  "route",
	2:  "locate",
	6:  "sources_to_targets",
	7:  "optimized_route",
	8:  "isochrone",
	9:  "trace_route",
	10: "trace_attributes",
	11: "height",
	12: "transit_available",
}
var DirectionsOptions_Action_value = map[string]int32{
	"route":              1,
	"locate":             2,
	"sources_to_targets": 6,
	"optimized_route":    7,
	"isochrone":          8,
	"trace_route":        9,
	"trace_attributes":   10,
	"height":             11,
	"transit_available":  12,
}

func (x DirectionsOptions_Action) Enum() *DirectionsOptions_Action {
	p := new(DirectionsOptions_Action)
	*p = x
	return p
}
func (x DirectionsOptions_Action) String() string {
	return proto.EnumName(DirectionsOptions_Action_name, int32(x))
}
func (x *DirectionsOptions_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DirectionsOptions_Action_value, data, "DirectionsOptions_Action")
	if err != nil {
		return err
	}
	*x = DirectionsOptions_Action(value)
	return nil
}
func (DirectionsOptions_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDirectionsOptions, []int{0, 2}
}

type DirectionsOptions_Costing int32

const (
	DirectionsOptions_auto_         DirectionsOptions_Costing = 0
	DirectionsOptions_auto_shorter  DirectionsOptions_Costing = 1
	DirectionsOptions_bicycle       DirectionsOptions_Costing = 2
	DirectionsOptions_bus           DirectionsOptions_Costing = 3
	DirectionsOptions_hov           DirectionsOptions_Costing = 4
	DirectionsOptions_motor_scooter DirectionsOptions_Costing = 5
	DirectionsOptions_multimodal    DirectionsOptions_Costing = 6
	DirectionsOptions_pedestrian    DirectionsOptions_Costing = 7
	DirectionsOptions_transit       DirectionsOptions_Costing = 8
	DirectionsOptions_truck         DirectionsOptions_Costing = 9
)

var DirectionsOptions_Costing_name = map[int32]string{
	0: "auto_",
	1: "auto_shorter",
	2: "bicycle",
	3: "bus",
	4: "hov",
	5: "motor_scooter",
	6: "multimodal",
	7: "pedestrian",
	8: "transit",
	9: "truck",
}
var DirectionsOptions_Costing_value = map[string]int32{
	"auto_":         0,
	"auto_shorter":  1,
	"bicycle":       2,
	"bus":           3,
	"hov":           4,
	"motor_scooter": 5,
	"multimodal":    6,
	"pedestrian":    7,
	"transit":       8,
	"truck":         9,
}

func (x DirectionsOptions_Costing) Enum() *DirectionsOptions_Costing {
	p := new(DirectionsOptions_Costing)
	*p = x
	return p
}
func (x DirectionsOptions_Costing) String() string {
	return proto.EnumName(DirectionsOptions_Costing_name, int32(x))
}
func (x *DirectionsOptions_Costing) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DirectionsOptions_Costing_value, data, "DirectionsOptions_Costing")
	if err != nil {
		return err
	}
	*x = DirectionsOptions_Costing(value)
	return nil
}
func (DirectionsOptions_Costing) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDirectionsOptions, []int{0, 3}
}

type DirectionsOptions_DateTimeType int32

const (
	DirectionsOptions_current   DirectionsOptions_DateTimeType = 0
	DirectionsOptions_depart_at DirectionsOptions_DateTimeType = 1
	DirectionsOptions_arrive_by DirectionsOptions_DateTimeType = 2
)

var DirectionsOptions_DateTimeType_name = map[int32]string{
	0: "current",
	1: "depart_at",
	2: "arrive_by",
}
var DirectionsOptions_DateTimeType_value = map[string]int32{
	"current":   0,
	"depart_at": 1,
	"arrive_by": 2,
}

func (x DirectionsOptions_DateTimeType) Enum() *DirectionsOptions_DateTimeType {
	p := new(DirectionsOptions_DateTimeType)
	*p = x
	return p
}
func (x DirectionsOptions_DateTimeType) String() string {
	return proto.EnumName(DirectionsOptions_DateTimeType_name, int32(x))
}
func (x *DirectionsOptions_DateTimeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DirectionsOptions_DateTimeType_value, data, "DirectionsOptions_DateTimeType")
	if err != nil {
		return err
	}
	*x = DirectionsOptions_DateTimeType(value)
	return nil
}
func (DirectionsOptions_DateTimeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDirectionsOptions, []int{0, 4}
}

type DirectionsOptions struct {
	Units            *DirectionsOptions_Units        `protobuf:"varint,1,opt,name=units,enum=valhalla.odin.DirectionsOptions_Units" json:"units,omitempty"`
	Language         *string                         `protobuf:"bytes,2,opt,name=language,def=en-US" json:"language,omitempty"`
	Narrative        *bool                           `protobuf:"varint,3,opt,name=narrative,def=1" json:"narrative,omitempty"`
	Format           *DirectionsOptions_Format       `protobuf:"varint,4,opt,name=format,enum=valhalla.odin.DirectionsOptions_Format,def=0" json:"format,omitempty"`
	Id               *string                         `protobuf:"bytes,5,opt,name=id" json:"id,omitempty"`
	Jsonp            *string                         `protobuf:"bytes,6,opt,name=jsonp" json:"jsonp,omitempty"`
	EncodedPolyline  *string                         `protobuf:"bytes,7,opt,name=encoded_polyline,json=encodedPolyline" json:"encoded_polyline,omitempty"`
	Action           *DirectionsOptions_Action       `protobuf:"varint,8,opt,name=action,enum=valhalla.odin.DirectionsOptions_Action" json:"action,omitempty"`
	DoNotTrack       *bool                           `protobuf:"varint,9,opt,name=do_not_track,json=doNotTrack,def=0" json:"do_not_track,omitempty"`
	Range            *bool                           `protobuf:"varint,10,opt,name=range,def=0" json:"range,omitempty"`
	Verbose          *bool                           `protobuf:"varint,11,opt,name=verbose,def=0" json:"verbose,omitempty"`
	Costing          *DirectionsOptions_Costing      `protobuf:"varint,12,opt,name=costing,enum=valhalla.odin.DirectionsOptions_Costing" json:"costing,omitempty"`
	Locations        []*valhalla_odin1.Location      `protobuf:"bytes,13,rep,name=locations" json:"locations,omitempty"`
	AvoidLocations   []*valhalla_odin1.Location      `protobuf:"bytes,14,rep,name=avoid_locations,json=avoidLocations" json:"avoid_locations,omitempty"`
	Sources          []*valhalla_odin1.Location      `protobuf:"bytes,15,rep,name=sources" json:"sources,omitempty"`
	Targets          []*valhalla_odin1.Location      `protobuf:"bytes,16,rep,name=targets" json:"targets,omitempty"`
	DateTimeType     *DirectionsOptions_DateTimeType `protobuf:"varint,17,opt,name=date_time_type,json=dateTimeType,enum=valhalla.odin.DirectionsOptions_DateTimeType" json:"date_time_type,omitempty"`
	DateTime         *string                         `protobuf:"bytes,18,opt,name=date_time,json=dateTime" json:"date_time,omitempty"`
	Shape            []*valhalla_odin1.Location      `protobuf:"bytes,19,rep,name=shape" json:"shape,omitempty"`
	ResampleDistance *float64                        `protobuf:"fixed64,20,opt,name=resample_distance,json=resampleDistance" json:"resample_distance,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *DirectionsOptions) Reset()         { *m = DirectionsOptions{} }
func (m *DirectionsOptions) String() string { return proto.CompactTextString(m) }
func (*DirectionsOptions) ProtoMessage()    {}
func (*DirectionsOptions) Descriptor() ([]byte, []int) {
	return fileDescriptorDirectionsOptions, []int{0}
}

const Default_DirectionsOptions_Language string = "en-US"
const Default_DirectionsOptions_Narrative bool = true
const Default_DirectionsOptions_Format DirectionsOptions_Format = DirectionsOptions_json
const Default_DirectionsOptions_DoNotTrack bool = false
const Default_DirectionsOptions_Range bool = false
const Default_DirectionsOptions_Verbose bool = false

func (m *DirectionsOptions) GetUnits() DirectionsOptions_Units {
	if m != nil && m.Units != nil {
		return *m.Units
	}
	return DirectionsOptions_kilometers
}

func (m *DirectionsOptions) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return Default_DirectionsOptions_Language
}

func (m *DirectionsOptions) GetNarrative() bool {
	if m != nil && m.Narrative != nil {
		return *m.Narrative
	}
	return Default_DirectionsOptions_Narrative
}

func (m *DirectionsOptions) GetFormat() DirectionsOptions_Format {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return Default_DirectionsOptions_Format
}

func (m *DirectionsOptions) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *DirectionsOptions) GetJsonp() string {
	if m != nil && m.Jsonp != nil {
		return *m.Jsonp
	}
	return ""
}

func (m *DirectionsOptions) GetEncodedPolyline() string {
	if m != nil && m.EncodedPolyline != nil {
		return *m.EncodedPolyline
	}
	return ""
}

func (m *DirectionsOptions) GetAction() DirectionsOptions_Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return DirectionsOptions_route
}

func (m *DirectionsOptions) GetDoNotTrack() bool {
	if m != nil && m.DoNotTrack != nil {
		return *m.DoNotTrack
	}
	return Default_DirectionsOptions_DoNotTrack
}

func (m *DirectionsOptions) GetRange() bool {
	if m != nil && m.Range != nil {
		return *m.Range
	}
	return Default_DirectionsOptions_Range
}

func (m *DirectionsOptions) GetVerbose() bool {
	if m != nil && m.Verbose != nil {
		return *m.Verbose
	}
	return Default_DirectionsOptions_Verbose
}

func (m *DirectionsOptions) GetCosting() DirectionsOptions_Costing {
	if m != nil && m.Costing != nil {
		return *m.Costing
	}
	return DirectionsOptions_auto_
}

func (m *DirectionsOptions) GetLocations() []*valhalla_odin1.Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *DirectionsOptions) GetAvoidLocations() []*valhalla_odin1.Location {
	if m != nil {
		return m.AvoidLocations
	}
	return nil
}

func (m *DirectionsOptions) GetSources() []*valhalla_odin1.Location {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *DirectionsOptions) GetTargets() []*valhalla_odin1.Location {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *DirectionsOptions) GetDateTimeType() DirectionsOptions_DateTimeType {
	if m != nil && m.DateTimeType != nil {
		return *m.DateTimeType
	}
	return DirectionsOptions_current
}

func (m *DirectionsOptions) GetDateTime() string {
	if m != nil && m.DateTime != nil {
		return *m.DateTime
	}
	return ""
}

func (m *DirectionsOptions) GetShape() []*valhalla_odin1.Location {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *DirectionsOptions) GetResampleDistance() float64 {
	if m != nil && m.ResampleDistance != nil {
		return *m.ResampleDistance
	}
	return 0
}

func init() {
	proto.RegisterType((*DirectionsOptions)(nil), "valhalla.odin.DirectionsOptions")
	proto.RegisterEnum("valhalla.odin.DirectionsOptions_Units", DirectionsOptions_Units_name, DirectionsOptions_Units_value)
	proto.RegisterEnum("valhalla.odin.DirectionsOptions_Format", DirectionsOptions_Format_name, DirectionsOptions_Format_value)
	proto.RegisterEnum("valhalla.odin.DirectionsOptions_Action", DirectionsOptions_Action_name, DirectionsOptions_Action_value)
	proto.RegisterEnum("valhalla.odin.DirectionsOptions_Costing", DirectionsOptions_Costing_name, DirectionsOptions_Costing_value)
	proto.RegisterEnum("valhalla.odin.DirectionsOptions_DateTimeType", DirectionsOptions_DateTimeType_name, DirectionsOptions_DateTimeType_value)
}

func init() { proto.RegisterFile("directions_options.proto", fileDescriptorDirectionsOptions) }

var fileDescriptorDirectionsOptions = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x8f, 0x93, 0x3a, 0x4e, 0x26, 0x69, 0xb2, 0x99, 0x2b, 0xb0, 0xe2, 0x1e, 0x08, 0x91, 0xe0,
	0x82, 0x50, 0x23, 0x71, 0x12, 0x0f, 0x54, 0x48, 0xfc, 0x2b, 0x3c, 0x9d, 0xe0, 0xe4, 0xeb, 0x3d,
	0x5b, 0x1b, 0x7b, 0x2e, 0x59, 0x6a, 0x7b, 0xad, 0xdd, 0x71, 0x44, 0xf8, 0x08, 0x3c, 0xf1, 0x25,
	0xf8, 0x9e, 0x68, 0x6d, 0xa7, 0x2d, 0x20, 0xb5, 0x3c, 0x65, 0xe7, 0xf7, 0x67, 0xf6, 0x97, 0xc9,
	0x6c, 0x40, 0x66, 0xda, 0x52, 0xca, 0xda, 0x94, 0x2e, 0x31, 0x55, 0xf3, 0xb9, 0xa9, 0xac, 0x61,
	0x83, 0xe7, 0x07, 0x95, 0xef, 0x55, 0x9e, 0xab, 0x8d, 0xc9, 0x74, 0xf9, 0xa1, 0x60, 0xab, 0xab,
	0xd4, 0x14, 0x85, 0x29, 0x5b, 0xc1, 0xea, 0x8f, 0x09, 0x2c, 0xae, 0xef, 0xdc, 0xbf, 0xb4, 0x66,
	0xfc, 0x1a, 0xc2, 0xba, 0xd4, 0xec, 0x64, 0xb0, 0x0c, 0xd6, 0xb3, 0x97, 0x9f, 0x6e, 0xfe, 0xd1,
	0x66, 0xf3, 0x1f, 0xc3, 0xe6, 0xad, 0x57, 0xc7, 0xad, 0x09, 0x3f, 0x86, 0x51, 0xae, 0xca, 0x5d,
	0xad, 0x76, 0x24, 0xfb, 0xcb, 0x60, 0x3d, 0xbe, 0x0a, 0xa9, 0xbc, 0x7c, 0xfb, 0x26, 0xbe, 0x83,
	0x71, 0x05, 0xe3, 0x52, 0x59, 0xab, 0x58, 0x1f, 0x48, 0x0e, 0x96, 0xc1, 0x7a, 0x74, 0x75, 0xc6,
	0xb6, 0xa6, 0xf8, 0x1e, 0xc6, 0x1f, 0x61, 0xf8, 0xce, 0xd8, 0x42, 0xb1, 0x3c, 0x6b, 0x52, 0xbc,
	0x78, 0x32, 0xc5, 0x4f, 0x8d, 0xfc, 0xea, 0xec, 0x57, 0x67, 0xca, 0xb8, 0x33, 0xe3, 0x0c, 0xfa,
	0x3a, 0x93, 0xa1, 0xcf, 0x11, 0xf7, 0x75, 0x86, 0x17, 0x10, 0x7a, 0xbe, 0x92, 0xc3, 0x06, 0x6a,
	0x0b, 0xfc, 0x0c, 0x04, 0x95, 0xa9, 0xc9, 0x28, 0x4b, 0x2a, 0x93, 0x1f, 0x73, 0x5d, 0x92, 0x8c,
	0x1a, 0xc1, 0xbc, 0xc3, 0x5f, 0x77, 0x30, 0x7e, 0x03, 0x43, 0xd5, 0xdc, 0x2b, 0x47, 0xff, 0x33,
	0xd7, 0x77, 0x4d, 0x19, 0x77, 0x36, 0x7c, 0x01, 0xd3, 0xcc, 0x24, 0xa5, 0xe1, 0x84, 0xad, 0x4a,
	0x6f, 0xe5, 0xb8, 0xf9, 0xfe, 0xe1, 0x3b, 0x95, 0x3b, 0x8a, 0x21, 0x33, 0x3f, 0x1b, 0xbe, 0xf1,
	0x04, 0x3e, 0x87, 0xd0, 0xaa, 0x72, 0x47, 0x12, 0x1e, 0x2a, 0x5a, 0x0c, 0x3f, 0x82, 0xe8, 0x40,
	0x76, 0x6b, 0x1c, 0xc9, 0xc9, 0x43, 0xfa, 0x84, 0xe2, 0xf7, 0x10, 0xa5, 0xc6, 0xb1, 0x2e, 0x77,
	0x72, 0xda, 0x04, 0x5d, 0x3f, 0x19, 0xf4, 0x87, 0x56, 0x1f, 0x9f, 0x8c, 0xf8, 0x25, 0x8c, 0x73,
	0x93, 0xaa, 0x86, 0x95, 0xe7, 0xcb, 0xc1, 0x7a, 0xf2, 0xf2, 0x83, 0x7f, 0x75, 0x79, 0xd5, 0xf1,
	0xf1, 0xbd, 0x12, 0xbf, 0x85, 0xb9, 0x3a, 0x18, 0x9d, 0x25, 0xf7, 0xe6, 0xd9, 0xe3, 0xe6, 0x59,
	0xa3, 0x7f, 0x75, 0xd7, 0xe1, 0x0b, 0x88, 0x9c, 0xa9, 0x6d, 0x4a, 0x4e, 0xce, 0x1f, 0x77, 0x9e,
	0x74, 0xde, 0xc2, 0xca, 0xee, 0x88, 0x9d, 0x14, 0x4f, 0x58, 0x3a, 0x1d, 0xbe, 0x81, 0x59, 0xa6,
	0x98, 0x12, 0xd6, 0x05, 0x25, 0x7c, 0xac, 0x48, 0x2e, 0x9a, 0x49, 0x5d, 0x3e, 0x39, 0xa9, 0x6b,
	0xc5, 0x74, 0xa3, 0x0b, 0xba, 0x39, 0x56, 0x14, 0x4f, 0xb3, 0x07, 0x15, 0x3e, 0x87, 0xf1, 0x5d,
	0x53, 0x89, 0xcd, 0x0e, 0x8d, 0x4e, 0x02, 0xbc, 0x84, 0xd0, 0xed, 0x55, 0x45, 0xf2, 0xd9, 0xe3,
	0x11, 0x5b, 0x15, 0x7e, 0x0e, 0x0b, 0x4b, 0x4e, 0x15, 0x55, 0x4e, 0x49, 0xa6, 0x1d, 0xab, 0x32,
	0x25, 0x79, 0xb1, 0x0c, 0xd6, 0x41, 0x2c, 0x4e, 0xc4, 0x75, 0x87, 0xaf, 0x56, 0x10, 0x36, 0xef,
	0x10, 0x67, 0x00, 0xb7, 0x3a, 0x37, 0x05, 0x31, 0x59, 0x27, 0x7a, 0x38, 0x86, 0xb0, 0xd0, 0x39,
	0x39, 0x11, 0xac, 0x3e, 0x81, 0x61, 0xfb, 0x4a, 0x70, 0x04, 0xcd, 0x3b, 0x11, 0x3d, 0x8c, 0x60,
	0xb0, 0xab, 0x7e, 0x13, 0x81, 0x87, 0x8c, 0xb3, 0x85, 0xe8, 0xaf, 0xfe, 0x0a, 0x60, 0xd8, 0x6e,
	0xad, 0x37, 0x5b, 0x53, 0x33, 0x89, 0x00, 0x01, 0x86, 0xcd, 0x0f, 0x4a, 0xa2, 0x8f, 0xef, 0x03,
	0x76, 0x83, 0x4f, 0xd8, 0x24, 0xdd, 0x40, 0xc5, 0x10, 0x9f, 0xc1, 0xdc, 0xff, 0x05, 0x15, 0xfa,
	0x77, 0xca, 0x92, 0xd6, 0x18, 0xe1, 0x39, 0x8c, 0xb5, 0x33, 0xe9, 0xde, 0x9a, 0x92, 0xc4, 0x08,
	0xe7, 0x30, 0xf1, 0x9b, 0x4f, 0x1d, 0x3f, 0xc6, 0x0b, 0x10, 0x2d, 0xa0, 0x98, 0xad, 0xde, 0xd6,
	0x4c, 0x4e, 0x80, 0xbf, 0x6e, 0x4f, 0x7a, 0xb7, 0x67, 0x31, 0xc1, 0xf7, 0x60, 0xc1, 0x56, 0x95,
	0x4e, 0x73, 0xa2, 0x0e, 0x4a, 0xe7, 0x6a, 0x9b, 0x93, 0x98, 0xae, 0xfe, 0x0c, 0x20, 0xea, 0x96,
	0xd6, 0x07, 0x55, 0x35, 0x9b, 0x44, 0xf4, 0x50, 0xc0, 0xb4, 0x39, 0xba, 0xbd, 0xb1, 0x4c, 0x56,
	0x04, 0x38, 0x81, 0x68, 0xab, 0xd3, 0x63, 0x9a, 0xfb, 0xec, 0x11, 0x0c, 0xb6, 0xb5, 0x13, 0x03,
	0x7f, 0xd8, 0x9b, 0x83, 0x38, 0xc3, 0x05, 0x9c, 0x17, 0x86, 0x8d, 0x4d, 0x5c, 0x6a, 0x8c, 0x77,
	0x84, 0x7e, 0x88, 0x45, 0x9d, 0xb3, 0x2e, 0x4c, 0xa6, 0x72, 0x31, 0xf4, 0x75, 0x45, 0x19, 0x39,
	0xb6, 0x5a, 0x95, 0x22, 0xf2, 0x1d, 0xbb, 0x44, 0x62, 0xe4, 0xef, 0x66, 0x5b, 0xa7, 0xb7, 0x62,
	0xbc, 0xfa, 0x0a, 0xa6, 0x0f, 0x97, 0xc3, 0xeb, 0xd2, 0xda, 0x5a, 0x2a, 0x59, 0xf4, 0xfc, 0x20,
	0x32, 0xaa, 0x94, 0xe5, 0x44, 0xb1, 0x08, 0x7c, 0xa9, 0xac, 0xd5, 0x07, 0x4a, 0xb6, 0x47, 0xd1,
	0x7f, 0xdd, 0xfb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xf2, 0x32, 0x32, 0xca, 0x05, 0x00, 0x00,
}
