// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: navigator.proto

/*
Package valhalla is a generated protocol buffer package.

It is generated from these files:
	navigator.proto

It has these top-level messages:
	FixLocation
	NavigationStatus
*/
package valhalla

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FixLocation) Validate() error {
	return nil
}
func (this *NavigationStatus) Validate() error {
	return nil
}
