// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: segment.proto

/*
Package opentraffic_osmlr is a generated protocol buffer package.

It is generated from these files:
	segment.proto

It has these top-level messages:
	Segment
*/
package opentraffic_osmlr

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Segment) Validate() error {
	for _, item := range this.Lrps {
		if err := go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return go_proto_validators.FieldError("Lrps", err)
		}
	}
	return nil
}
func (this *Segment_LatLng) Validate() error {
	return nil
}
func (this *Segment_LocationReference) Validate() error {
	if this.Coord != nil {
		if err := go_proto_validators.CallValidatorIfExists(&(*(this.Coord))); err != nil {
			return go_proto_validators.FieldError("Coord", err)
		}
	}
	return nil
}
