// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tile.proto

/*
Package opentraffic_osmlr is a generated protocol buffer package.

It is generated from these files:
	tile.proto

It has these top-level messages:
	MarkedDeleted
	Tile
*/
package opentraffic_osmlr

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import opentraffic_osmlr1 "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MarkedDeleted struct {
	SegmentDeletedDate *uint32 `protobuf:"varint,1,opt,name=segment_deleted_date,json=segmentDeletedDate" json:"segment_deleted_date,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *MarkedDeleted) Reset()                    { *m = MarkedDeleted{} }
func (m *MarkedDeleted) String() string            { return proto.CompactTextString(m) }
func (*MarkedDeleted) ProtoMessage()               {}
func (*MarkedDeleted) Descriptor() ([]byte, []int) { return fileDescriptorTile, []int{0} }

func (m *MarkedDeleted) GetSegmentDeletedDate() uint32 {
	if m != nil && m.SegmentDeletedDate != nil {
		return *m.SegmentDeletedDate
	}
	return 0
}

type Tile struct {
	// a tile consists of a list of Entries.
	Entries []*Tile_Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	// Creation date and time (UTC epoch seconds) for this OSMLR tile.
	CreationDate *uint32 `protobuf:"varint,2,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
	// Reference to the OSM changeset Id. While not an exact representation of
	// the state of the OSM planet file that OSMLR was derived from, this
	// provides context on age and provenance of tile data derived from OSM.
	ChangesetId *uint64 `protobuf:"varint,3,opt,name=changeset_id,json=changesetId" json:"changeset_id,omitempty"`
	// A string meant to describe this tile. It may be used to describe the geographic
	// extents of the tile but has no strict format. So as to remain projection
	// or really tiling system agnostic, its simple string which can be interpreted
	// differently depending on the tiling system used to generate and consume the tile
	Description      *string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tile) Reset()                    { *m = Tile{} }
func (m *Tile) String() string            { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()               {}
func (*Tile) Descriptor() ([]byte, []int) { return fileDescriptorTile, []int{1} }

func (m *Tile) GetEntries() []*Tile_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Tile) GetCreationDate() uint32 {
	if m != nil && m.CreationDate != nil {
		return *m.CreationDate
	}
	return 0
}

func (m *Tile) GetChangesetId() uint64 {
	if m != nil && m.ChangesetId != nil {
		return *m.ChangesetId
	}
	return 0
}

func (m *Tile) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type Tile_Entry struct {
	// an entry in the tile should be _either_ a Segment _or_ a Marker. a tile
	// containing an Entry with both or neither is invalid.
	// Date is when the OSMLR segment was created (if segment exists) or the
	// date when the segment was deleted (if marker exists)
	Segment             *opentraffic_osmlr1.Segment `protobuf:"bytes,1,opt,name=segment" json:"segment,omitempty"`
	Marker              *MarkedDeleted              `protobuf:"bytes,2,opt,name=marker" json:"marker,omitempty"`
	SegmentCreationDate *uint32                     `protobuf:"varint,3,opt,name=segment_creation_date,json=segmentCreationDate" json:"segment_creation_date,omitempty"`
	XXX_unrecognized    []byte                      `json:"-"`
}

func (m *Tile_Entry) Reset()                    { *m = Tile_Entry{} }
func (m *Tile_Entry) String() string            { return proto.CompactTextString(m) }
func (*Tile_Entry) ProtoMessage()               {}
func (*Tile_Entry) Descriptor() ([]byte, []int) { return fileDescriptorTile, []int{1, 0} }

func (m *Tile_Entry) GetSegment() *opentraffic_osmlr1.Segment {
	if m != nil {
		return m.Segment
	}
	return nil
}

func (m *Tile_Entry) GetMarker() *MarkedDeleted {
	if m != nil {
		return m.Marker
	}
	return nil
}

func (m *Tile_Entry) GetSegmentCreationDate() uint32 {
	if m != nil && m.SegmentCreationDate != nil {
		return *m.SegmentCreationDate
	}
	return 0
}

func init() {
	proto.RegisterType((*MarkedDeleted)(nil), "opentraffic.osmlr.MarkedDeleted")
	proto.RegisterType((*Tile)(nil), "opentraffic.osmlr.Tile")
	proto.RegisterType((*Tile_Entry)(nil), "opentraffic.osmlr.Tile.Entry")
}

func init() { proto.RegisterFile("tile.proto", fileDescriptorTile) }

var fileDescriptorTile = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4b, 0xf4, 0x40,
	0x10, 0xc6, 0xd9, 0x4b, 0xde, 0xf7, 0x70, 0x72, 0x29, 0x5c, 0x15, 0x42, 0x40, 0x58, 0xcf, 0x26,
	0x55, 0x90, 0x20, 0x68, 0x2b, 0x9e, 0x85, 0x85, 0xcd, 0x6a, 0x1f, 0x96, 0xec, 0xdc, 0xb9, 0x98,
	0x7f, 0x6c, 0xa6, 0xf1, 0x33, 0xf9, 0x81, 0xfc, 0x3a, 0x92, 0xcd, 0x46, 0xee, 0xf0, 0xda, 0x67,
	0x7e, 0xc3, 0x6f, 0x9e, 0x01, 0x20, 0x53, 0x63, 0xde, 0xdb, 0x8e, 0x3a, 0x7e, 0xda, 0xf5, 0xd8,
	0x92, 0x55, 0xdb, 0xad, 0xa9, 0xf2, 0x6e, 0x68, 0x6a, 0x9b, 0xc6, 0x03, 0xee, 0x1a, 0x6c, 0x69,
	0x22, 0xd6, 0x0f, 0x10, 0xbf, 0x28, 0xfb, 0x81, 0x7a, 0x83, 0x35, 0x12, 0x6a, 0x7e, 0x03, 0xe7,
	0x9e, 0x28, 0xf5, 0x14, 0x95, 0x5a, 0x11, 0x26, 0x4c, 0xb0, 0x2c, 0x96, 0xdc, 0xcf, 0x3c, 0xbd,
	0x51, 0x84, 0xeb, 0xef, 0x05, 0x84, 0x6f, 0xa6, 0x46, 0x7e, 0x07, 0xcb, 0xd1, 0x66, 0x70, 0x48,
	0x98, 0x08, 0xb2, 0xa8, 0xb8, 0xcc, 0xff, 0xf8, 0xf3, 0x91, 0xcc, 0x9f, 0x5a, 0xb2, 0x9f, 0x72,
	0xa6, 0xf9, 0x35, 0xc4, 0x95, 0x45, 0x45, 0xa6, 0x6b, 0x27, 0xd9, 0xc2, 0xc9, 0x56, 0x73, 0x38,
	0x6a, 0xf8, 0x15, 0xac, 0xaa, 0x77, 0xd5, 0xee, 0x70, 0x40, 0x2a, 0x8d, 0x4e, 0x02, 0xc1, 0xb2,
	0x50, 0x46, 0xbf, 0xd9, 0xb3, 0xe6, 0x02, 0x22, 0x8d, 0x43, 0x65, 0x4d, 0x3f, 0x6e, 0x25, 0xa1,
	0x60, 0xd9, 0x89, 0xdc, 0x8f, 0xd2, 0x2f, 0x06, 0xff, 0x9c, 0x9c, 0xdf, 0xc2, 0xd2, 0x77, 0x71,
	0xd5, 0xa2, 0x22, 0x3d, 0x72, 0xec, 0xeb, 0x44, 0xc8, 0x19, 0xe5, 0xf7, 0xf0, 0xbf, 0x19, 0xdf,
	0x65, 0xdd, 0x89, 0x51, 0x21, 0x8e, 0x2c, 0x1d, 0xfc, 0x53, 0x7a, 0x9e, 0x17, 0x70, 0x31, 0xff,
	0xf5, 0xb0, 0x6b, 0xe0, 0xba, 0x9e, 0xf9, 0xe1, 0xe3, 0x5e, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfc, 0xdf, 0x89, 0x49, 0xcb, 0x01, 0x00, 0x00,
}
