// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transit.proto

/*
Package valhalla_mjolnir is a generated protocol buffer package.

It is generated from these files:
	transit.proto

It has these top-level messages:
	Transit
*/
package valhalla_mjolnir

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Transit_VehicleType int32

const (
	Transit_kTram      Transit_VehicleType = 0
	Transit_kMetro     Transit_VehicleType = 1
	Transit_kRail      Transit_VehicleType = 2
	Transit_kBus       Transit_VehicleType = 3
	Transit_kFerry     Transit_VehicleType = 4
	Transit_kCableCar  Transit_VehicleType = 5
	Transit_kGondola   Transit_VehicleType = 6
	Transit_kFunicular Transit_VehicleType = 7
)

var Transit_VehicleType_name = map[int32]string{
	0: "kTram",
	1: "kMetro",
	2: "kRail",
	3: "kBus",
	4: "kFerry",
	5: "kCableCar",
	6: "kGondola",
	7: "kFunicular",
}
var Transit_VehicleType_value = map[string]int32{
	"kTram":      0,
	"kMetro":     1,
	"kRail":      2,
	"kBus":       3,
	"kFerry":     4,
	"kCableCar":  5,
	"kGondola":   6,
	"kFunicular": 7,
}

func (x Transit_VehicleType) Enum() *Transit_VehicleType {
	p := new(Transit_VehicleType)
	*p = x
	return p
}
func (x Transit_VehicleType) String() string {
	return proto.EnumName(Transit_VehicleType_name, int32(x))
}
func (x *Transit_VehicleType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Transit_VehicleType_value, data, "Transit_VehicleType")
	if err != nil {
		return err
	}
	*x = Transit_VehicleType(value)
	return nil
}
func (Transit_VehicleType) EnumDescriptor() ([]byte, []int) { return fileDescriptorTransit, []int{0, 0} }

type Transit struct {
	Nodes            []*Transit_Node     `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	StopPairs        []*Transit_StopPair `protobuf:"bytes,2,rep,name=stop_pairs,json=stopPairs" json:"stop_pairs,omitempty"`
	Routes           []*Transit_Route    `protobuf:"bytes,3,rep,name=routes" json:"routes,omitempty"`
	Shapes           []*Transit_Shape    `protobuf:"bytes,4,rep,name=shapes" json:"shapes,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Transit) Reset()                    { *m = Transit{} }
func (m *Transit) String() string            { return proto.CompactTextString(m) }
func (*Transit) ProtoMessage()               {}
func (*Transit) Descriptor() ([]byte, []int) { return fileDescriptorTransit, []int{0} }

func (m *Transit) GetNodes() []*Transit_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Transit) GetStopPairs() []*Transit_StopPair {
	if m != nil {
		return m.StopPairs
	}
	return nil
}

func (m *Transit) GetRoutes() []*Transit_Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *Transit) GetShapes() []*Transit_Shape {
	if m != nil {
		return m.Shapes
	}
	return nil
}

type Transit_Node struct {
	Lon                *float32 `protobuf:"fixed32,1,opt,name=lon" json:"lon,omitempty"`
	Lat                *float32 `protobuf:"fixed32,2,opt,name=lat" json:"lat,omitempty"`
	Type               *uint32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Graphid            *uint64  `protobuf:"varint,4,opt,name=graphid" json:"graphid,omitempty"`
	PrevTypeGraphid    *uint64  `protobuf:"varint,5,opt,name=prev_type_graphid,json=prevTypeGraphid" json:"prev_type_graphid,omitempty"`
	Name               *string  `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	OnestopId          *string  `protobuf:"bytes,7,opt,name=onestop_id,json=onestopId" json:"onestop_id,omitempty"`
	OsmWayId           *uint64  `protobuf:"varint,8,opt,name=osm_way_id,json=osmWayId" json:"osm_way_id,omitempty"`
	Timezone           *string  `protobuf:"bytes,9,opt,name=timezone" json:"timezone,omitempty"`
	WheelchairBoarding *bool    `protobuf:"varint,10,opt,name=wheelchair_boarding,json=wheelchairBoarding" json:"wheelchair_boarding,omitempty"`
	Generated          *bool    `protobuf:"varint,11,opt,name=generated" json:"generated,omitempty"`
	Traversability     *uint32  `protobuf:"varint,12,opt,name=traversability" json:"traversability,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *Transit_Node) Reset()                    { *m = Transit_Node{} }
func (m *Transit_Node) String() string            { return proto.CompactTextString(m) }
func (*Transit_Node) ProtoMessage()               {}
func (*Transit_Node) Descriptor() ([]byte, []int) { return fileDescriptorTransit, []int{0, 0} }

func (m *Transit_Node) GetLon() float32 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Transit_Node) GetLat() float32 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Transit_Node) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Transit_Node) GetGraphid() uint64 {
	if m != nil && m.Graphid != nil {
		return *m.Graphid
	}
	return 0
}

func (m *Transit_Node) GetPrevTypeGraphid() uint64 {
	if m != nil && m.PrevTypeGraphid != nil {
		return *m.PrevTypeGraphid
	}
	return 0
}

func (m *Transit_Node) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Transit_Node) GetOnestopId() string {
	if m != nil && m.OnestopId != nil {
		return *m.OnestopId
	}
	return ""
}

func (m *Transit_Node) GetOsmWayId() uint64 {
	if m != nil && m.OsmWayId != nil {
		return *m.OsmWayId
	}
	return 0
}

func (m *Transit_Node) GetTimezone() string {
	if m != nil && m.Timezone != nil {
		return *m.Timezone
	}
	return ""
}

func (m *Transit_Node) GetWheelchairBoarding() bool {
	if m != nil && m.WheelchairBoarding != nil {
		return *m.WheelchairBoarding
	}
	return false
}

func (m *Transit_Node) GetGenerated() bool {
	if m != nil && m.Generated != nil {
		return *m.Generated
	}
	return false
}

func (m *Transit_Node) GetTraversability() uint32 {
	if m != nil && m.Traversability != nil {
		return *m.Traversability
	}
	return 0
}

type Transit_StopPair struct {
	BikesAllowed            *bool    `protobuf:"varint,1,opt,name=bikes_allowed,json=bikesAllowed" json:"bikes_allowed,omitempty"`
	BlockId                 *uint32  `protobuf:"varint,2,opt,name=block_id,json=blockId" json:"block_id,omitempty"`
	DestinationArrivalTime  *uint32  `protobuf:"varint,3,opt,name=destination_arrival_time,json=destinationArrivalTime" json:"destination_arrival_time,omitempty"`
	DestinationGraphid      *uint64  `protobuf:"varint,4,opt,name=destination_graphid,json=destinationGraphid" json:"destination_graphid,omitempty"`
	DestinationOnestopId    *string  `protobuf:"bytes,5,opt,name=destination_onestop_id,json=destinationOnestopId" json:"destination_onestop_id,omitempty"`
	OperatedByOnestopId     *string  `protobuf:"bytes,6,opt,name=operated_by_onestop_id,json=operatedByOnestopId" json:"operated_by_onestop_id,omitempty"`
	OriginDepartureTime     *uint32  `protobuf:"varint,7,opt,name=origin_departure_time,json=originDepartureTime" json:"origin_departure_time,omitempty"`
	OriginGraphid           *uint64  `protobuf:"varint,8,opt,name=origin_graphid,json=originGraphid" json:"origin_graphid,omitempty"`
	OriginOnestopId         *string  `protobuf:"bytes,9,opt,name=origin_onestop_id,json=originOnestopId" json:"origin_onestop_id,omitempty"`
	RouteIndex              *uint32  `protobuf:"varint,10,opt,name=route_index,json=routeIndex" json:"route_index,omitempty"`
	ServiceAddedDates       []uint32 `protobuf:"varint,11,rep,name=service_added_dates,json=serviceAddedDates" json:"service_added_dates,omitempty"`
	ServiceDaysOfWeek       []bool   `protobuf:"varint,12,rep,name=service_days_of_week,json=serviceDaysOfWeek" json:"service_days_of_week,omitempty"`
	ServiceEndDate          *uint32  `protobuf:"varint,13,opt,name=service_end_date,json=serviceEndDate" json:"service_end_date,omitempty"`
	ServiceExceptDates      []uint32 `protobuf:"varint,14,rep,name=service_except_dates,json=serviceExceptDates" json:"service_except_dates,omitempty"`
	ServiceStartDate        *uint32  `protobuf:"varint,15,opt,name=service_start_date,json=serviceStartDate" json:"service_start_date,omitempty"`
	TripHeadsign            *string  `protobuf:"bytes,16,opt,name=trip_headsign,json=tripHeadsign" json:"trip_headsign,omitempty"`
	TripId                  *uint32  `protobuf:"varint,17,opt,name=trip_id,json=tripId" json:"trip_id,omitempty"`
	WheelchairAccessible    *bool    `protobuf:"varint,18,opt,name=wheelchair_accessible,json=wheelchairAccessible" json:"wheelchair_accessible,omitempty"`
	ShapeId                 *uint32  `protobuf:"varint,20,opt,name=shape_id,json=shapeId" json:"shape_id,omitempty"`
	OriginDistTraveled      *float32 `protobuf:"fixed32,21,opt,name=origin_dist_traveled,json=originDistTraveled" json:"origin_dist_traveled,omitempty"`
	DestinationDistTraveled *float32 `protobuf:"fixed32,22,opt,name=destination_dist_traveled,json=destinationDistTraveled" json:"destination_dist_traveled,omitempty"`
	FrequencyEndTime        *uint32  `protobuf:"varint,23,opt,name=frequency_end_time,json=frequencyEndTime" json:"frequency_end_time,omitempty"`
	FrequencyHeadwaySeconds *uint32  `protobuf:"varint,24,opt,name=frequency_headway_seconds,json=frequencyHeadwaySeconds" json:"frequency_headway_seconds,omitempty"`
	XXX_unrecognized        []byte   `json:"-"`
}

func (m *Transit_StopPair) Reset()                    { *m = Transit_StopPair{} }
func (m *Transit_StopPair) String() string            { return proto.CompactTextString(m) }
func (*Transit_StopPair) ProtoMessage()               {}
func (*Transit_StopPair) Descriptor() ([]byte, []int) { return fileDescriptorTransit, []int{0, 1} }

func (m *Transit_StopPair) GetBikesAllowed() bool {
	if m != nil && m.BikesAllowed != nil {
		return *m.BikesAllowed
	}
	return false
}

func (m *Transit_StopPair) GetBlockId() uint32 {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return 0
}

func (m *Transit_StopPair) GetDestinationArrivalTime() uint32 {
	if m != nil && m.DestinationArrivalTime != nil {
		return *m.DestinationArrivalTime
	}
	return 0
}

func (m *Transit_StopPair) GetDestinationGraphid() uint64 {
	if m != nil && m.DestinationGraphid != nil {
		return *m.DestinationGraphid
	}
	return 0
}

func (m *Transit_StopPair) GetDestinationOnestopId() string {
	if m != nil && m.DestinationOnestopId != nil {
		return *m.DestinationOnestopId
	}
	return ""
}

func (m *Transit_StopPair) GetOperatedByOnestopId() string {
	if m != nil && m.OperatedByOnestopId != nil {
		return *m.OperatedByOnestopId
	}
	return ""
}

func (m *Transit_StopPair) GetOriginDepartureTime() uint32 {
	if m != nil && m.OriginDepartureTime != nil {
		return *m.OriginDepartureTime
	}
	return 0
}

func (m *Transit_StopPair) GetOriginGraphid() uint64 {
	if m != nil && m.OriginGraphid != nil {
		return *m.OriginGraphid
	}
	return 0
}

func (m *Transit_StopPair) GetOriginOnestopId() string {
	if m != nil && m.OriginOnestopId != nil {
		return *m.OriginOnestopId
	}
	return ""
}

func (m *Transit_StopPair) GetRouteIndex() uint32 {
	if m != nil && m.RouteIndex != nil {
		return *m.RouteIndex
	}
	return 0
}

func (m *Transit_StopPair) GetServiceAddedDates() []uint32 {
	if m != nil {
		return m.ServiceAddedDates
	}
	return nil
}

func (m *Transit_StopPair) GetServiceDaysOfWeek() []bool {
	if m != nil {
		return m.ServiceDaysOfWeek
	}
	return nil
}

func (m *Transit_StopPair) GetServiceEndDate() uint32 {
	if m != nil && m.ServiceEndDate != nil {
		return *m.ServiceEndDate
	}
	return 0
}

func (m *Transit_StopPair) GetServiceExceptDates() []uint32 {
	if m != nil {
		return m.ServiceExceptDates
	}
	return nil
}

func (m *Transit_StopPair) GetServiceStartDate() uint32 {
	if m != nil && m.ServiceStartDate != nil {
		return *m.ServiceStartDate
	}
	return 0
}

func (m *Transit_StopPair) GetTripHeadsign() string {
	if m != nil && m.TripHeadsign != nil {
		return *m.TripHeadsign
	}
	return ""
}

func (m *Transit_StopPair) GetTripId() uint32 {
	if m != nil && m.TripId != nil {
		return *m.TripId
	}
	return 0
}

func (m *Transit_StopPair) GetWheelchairAccessible() bool {
	if m != nil && m.WheelchairAccessible != nil {
		return *m.WheelchairAccessible
	}
	return false
}

func (m *Transit_StopPair) GetShapeId() uint32 {
	if m != nil && m.ShapeId != nil {
		return *m.ShapeId
	}
	return 0
}

func (m *Transit_StopPair) GetOriginDistTraveled() float32 {
	if m != nil && m.OriginDistTraveled != nil {
		return *m.OriginDistTraveled
	}
	return 0
}

func (m *Transit_StopPair) GetDestinationDistTraveled() float32 {
	if m != nil && m.DestinationDistTraveled != nil {
		return *m.DestinationDistTraveled
	}
	return 0
}

func (m *Transit_StopPair) GetFrequencyEndTime() uint32 {
	if m != nil && m.FrequencyEndTime != nil {
		return *m.FrequencyEndTime
	}
	return 0
}

func (m *Transit_StopPair) GetFrequencyHeadwaySeconds() uint32 {
	if m != nil && m.FrequencyHeadwaySeconds != nil {
		return *m.FrequencyHeadwaySeconds
	}
	return 0
}

type Transit_Route struct {
	Name                *string              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	OnestopId           *string              `protobuf:"bytes,2,opt,name=onestop_id,json=onestopId" json:"onestop_id,omitempty"`
	OperatedByName      *string              `protobuf:"bytes,3,opt,name=operated_by_name,json=operatedByName" json:"operated_by_name,omitempty"`
	OperatedByOnestopId *string              `protobuf:"bytes,4,opt,name=operated_by_onestop_id,json=operatedByOnestopId" json:"operated_by_onestop_id,omitempty"`
	OperatedByWebsite   *string              `protobuf:"bytes,5,opt,name=operated_by_website,json=operatedByWebsite" json:"operated_by_website,omitempty"`
	RouteColor          *uint32              `protobuf:"varint,6,opt,name=route_color,json=routeColor" json:"route_color,omitempty"`
	RouteDesc           *string              `protobuf:"bytes,7,opt,name=route_desc,json=routeDesc" json:"route_desc,omitempty"`
	RouteLongName       *string              `protobuf:"bytes,8,opt,name=route_long_name,json=routeLongName" json:"route_long_name,omitempty"`
	RouteTextColor      *uint32              `protobuf:"varint,9,opt,name=route_text_color,json=routeTextColor" json:"route_text_color,omitempty"`
	VehicleType         *Transit_VehicleType `protobuf:"varint,10,opt,name=vehicle_type,json=vehicleType,enum=valhalla.mjolnir.Transit_VehicleType" json:"vehicle_type,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *Transit_Route) Reset()                    { *m = Transit_Route{} }
func (m *Transit_Route) String() string            { return proto.CompactTextString(m) }
func (*Transit_Route) ProtoMessage()               {}
func (*Transit_Route) Descriptor() ([]byte, []int) { return fileDescriptorTransit, []int{0, 2} }

func (m *Transit_Route) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Transit_Route) GetOnestopId() string {
	if m != nil && m.OnestopId != nil {
		return *m.OnestopId
	}
	return ""
}

func (m *Transit_Route) GetOperatedByName() string {
	if m != nil && m.OperatedByName != nil {
		return *m.OperatedByName
	}
	return ""
}

func (m *Transit_Route) GetOperatedByOnestopId() string {
	if m != nil && m.OperatedByOnestopId != nil {
		return *m.OperatedByOnestopId
	}
	return ""
}

func (m *Transit_Route) GetOperatedByWebsite() string {
	if m != nil && m.OperatedByWebsite != nil {
		return *m.OperatedByWebsite
	}
	return ""
}

func (m *Transit_Route) GetRouteColor() uint32 {
	if m != nil && m.RouteColor != nil {
		return *m.RouteColor
	}
	return 0
}

func (m *Transit_Route) GetRouteDesc() string {
	if m != nil && m.RouteDesc != nil {
		return *m.RouteDesc
	}
	return ""
}

func (m *Transit_Route) GetRouteLongName() string {
	if m != nil && m.RouteLongName != nil {
		return *m.RouteLongName
	}
	return ""
}

func (m *Transit_Route) GetRouteTextColor() uint32 {
	if m != nil && m.RouteTextColor != nil {
		return *m.RouteTextColor
	}
	return 0
}

func (m *Transit_Route) GetVehicleType() Transit_VehicleType {
	if m != nil && m.VehicleType != nil {
		return *m.VehicleType
	}
	return Transit_kTram
}

type Transit_Shape struct {
	ShapeId          *uint32 `protobuf:"varint,1,opt,name=shape_id,json=shapeId" json:"shape_id,omitempty"`
	EncodedShape     []byte  `protobuf:"bytes,2,opt,name=encoded_shape,json=encodedShape" json:"encoded_shape,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Transit_Shape) Reset()                    { *m = Transit_Shape{} }
func (m *Transit_Shape) String() string            { return proto.CompactTextString(m) }
func (*Transit_Shape) ProtoMessage()               {}
func (*Transit_Shape) Descriptor() ([]byte, []int) { return fileDescriptorTransit, []int{0, 3} }

func (m *Transit_Shape) GetShapeId() uint32 {
	if m != nil && m.ShapeId != nil {
		return *m.ShapeId
	}
	return 0
}

func (m *Transit_Shape) GetEncodedShape() []byte {
	if m != nil {
		return m.EncodedShape
	}
	return nil
}

func init() {
	proto.RegisterType((*Transit)(nil), "valhalla.mjolnir.Transit")
	proto.RegisterType((*Transit_Node)(nil), "valhalla.mjolnir.Transit.Node")
	proto.RegisterType((*Transit_StopPair)(nil), "valhalla.mjolnir.Transit.StopPair")
	proto.RegisterType((*Transit_Route)(nil), "valhalla.mjolnir.Transit.Route")
	proto.RegisterType((*Transit_Shape)(nil), "valhalla.mjolnir.Transit.Shape")
	proto.RegisterEnum("valhalla.mjolnir.Transit_VehicleType", Transit_VehicleType_name, Transit_VehicleType_value)
}

func init() { proto.RegisterFile("transit.proto", fileDescriptorTransit) }

var fileDescriptorTransit = []byte{
	// 1093 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x6e, 0xdb, 0xb6,
	0x17, 0xff, 0x3b, 0xb6, 0x63, 0xfb, 0xc4, 0x4e, 0x14, 0x26, 0x6d, 0xd8, 0xa0, 0xff, 0xd5, 0x68,
	0xd1, 0xc2, 0x18, 0x0a, 0x77, 0xe8, 0x0a, 0x6c, 0xe8, 0x5d, 0xda, 0xb4, 0x69, 0x80, 0xad, 0x1d,
	0x94, 0x60, 0xbd, 0x14, 0x68, 0xf1, 0xd4, 0xe6, 0x2c, 0x8b, 0x1a, 0xc9, 0x38, 0xf1, 0xde, 0x64,
	0x0f, 0xb0, 0xf7, 0xda, 0xe5, 0x1e, 0x63, 0xe0, 0xa1, 0x64, 0x2b, 0x05, 0x82, 0xdd, 0x89, 0xbf,
	0x8f, 0x23, 0x1d, 0x9e, 0x0f, 0xc1, 0xc0, 0x19, 0x91, 0x5b, 0xe5, 0xc6, 0x85, 0xd1, 0x4e, 0xb3,
	0x68, 0x29, 0xb2, 0x99, 0xc8, 0x32, 0x31, 0x5e, 0xfc, 0xa6, 0xb3, 0x5c, 0x99, 0xc7, 0x7f, 0xef,
	0x43, 0xe7, 0x32, 0x68, 0xd8, 0x2b, 0x68, 0xe7, 0x5a, 0xa2, 0xe5, 0x8d, 0x61, 0x73, 0xb4, 0xf3,
	0xf2, 0x9b, 0xf1, 0xd7, 0xea, 0x71, 0xa9, 0x1c, 0x7f, 0xd4, 0x12, 0xe3, 0x20, 0x66, 0x27, 0x00,
	0xd6, 0xe9, 0x22, 0x29, 0x84, 0x32, 0x96, 0x6f, 0x91, 0xf5, 0xf1, 0xdd, 0xd6, 0x0b, 0xa7, 0x8b,
	0x5f, 0x84, 0x32, 0x71, 0xcf, 0x96, 0x4f, 0x96, 0xfd, 0x00, 0xdb, 0x46, 0x5f, 0x39, 0xb4, 0xbc,
	0x49, 0xf6, 0x47, 0x77, 0xdb, 0x63, 0xaf, 0x8b, 0x4b, 0xb9, 0x37, 0xda, 0x99, 0x28, 0xd0, 0xf2,
	0xd6, 0x7f, 0x19, 0x2f, 0xbc, 0x2e, 0x2e, 0xe5, 0xc7, 0xff, 0x6c, 0x41, 0xcb, 0x27, 0xc1, 0x22,
	0x68, 0x66, 0x3a, 0xe7, 0x8d, 0x61, 0x63, 0xb4, 0x15, 0xfb, 0x47, 0x42, 0x84, 0xe3, 0x5b, 0x25,
	0x22, 0x1c, 0x63, 0xd0, 0x72, 0xab, 0x02, 0x79, 0x73, 0xd8, 0x18, 0x0d, 0x62, 0x7a, 0x66, 0x1c,
	0x3a, 0x53, 0x23, 0x8a, 0x99, 0x92, 0xbc, 0x35, 0x6c, 0x8c, 0x5a, 0x71, 0x75, 0x64, 0xdf, 0xc2,
	0x7e, 0x61, 0x70, 0x99, 0x78, 0x59, 0x52, 0x69, 0xda, 0xa4, 0xd9, 0xf3, 0xc4, 0xe5, 0xaa, 0xc0,
	0xb3, 0x52, 0xcb, 0xa0, 0x95, 0x8b, 0x05, 0xf2, 0xed, 0x61, 0x63, 0xd4, 0x8b, 0xe9, 0x99, 0xfd,
	0x1f, 0x40, 0xe7, 0x48, 0x57, 0xaa, 0x24, 0xef, 0x10, 0xd3, 0x2b, 0x91, 0x73, 0xc9, 0x1e, 0x02,
	0x68, 0xbb, 0x48, 0xae, 0xc5, 0xca, 0xd3, 0x5d, 0x8a, 0xdb, 0xd5, 0x76, 0xf1, 0x59, 0xac, 0xce,
	0x25, 0x3b, 0x86, 0xae, 0x53, 0x0b, 0xfc, 0x43, 0xe7, 0xc8, 0x7b, 0x64, 0x5d, 0x9f, 0xd9, 0x0b,
	0x38, 0xb8, 0x9e, 0x21, 0x66, 0xe9, 0x4c, 0x28, 0x93, 0x4c, 0xb4, 0x30, 0x52, 0xe5, 0x53, 0x0e,
	0xc3, 0xc6, 0xa8, 0x1b, 0xb3, 0x0d, 0xf5, 0xa6, 0x64, 0xd8, 0x43, 0xe8, 0x4d, 0x31, 0x47, 0x23,
	0x1c, 0x4a, 0xbe, 0x43, 0xb2, 0x0d, 0xc0, 0x9e, 0xc1, 0xae, 0x33, 0x62, 0x89, 0xc6, 0x8a, 0x89,
	0xca, 0x94, 0x5b, 0xf1, 0x3e, 0xdd, 0xcf, 0x57, 0xe8, 0xf1, 0x9f, 0x5d, 0xe8, 0x56, 0x45, 0x67,
	0x4f, 0x60, 0x30, 0x51, 0x73, 0xb4, 0x89, 0xc8, 0x32, 0x7d, 0x8d, 0x92, 0x2e, 0xbe, 0x1b, 0xf7,
	0x09, 0x3c, 0x09, 0x18, 0x7b, 0x00, 0xdd, 0x49, 0xa6, 0xd3, 0xb9, 0x4f, 0x70, 0x8b, 0x62, 0x76,
	0xe8, 0x7c, 0x2e, 0xd9, 0x8f, 0xc0, 0x25, 0x5a, 0xa7, 0x72, 0xe1, 0x94, 0xce, 0x13, 0x61, 0x8c,
	0x5a, 0x8a, 0x2c, 0xf1, 0x39, 0x96, 0xe5, 0xb9, 0x5f, 0xe3, 0x4f, 0x02, 0x7d, 0xa9, 0x16, 0x94,
	0x7d, 0xdd, 0x79, 0xbb, 0x78, 0xac, 0x46, 0x55, 0xb5, 0x79, 0x05, 0xf5, 0x50, 0x49, 0xad, 0x26,
	0x6d, 0xba, 0xd8, 0xc3, 0x1a, 0xfb, 0x69, 0x5d, 0x9e, 0xef, 0xe1, 0xbe, 0x2e, 0xc2, 0x0d, 0x25,
	0x93, 0x55, 0xdd, 0x15, 0x6a, 0x7c, 0x50, 0xb1, 0x6f, 0x56, 0x1b, 0xd3, 0x4b, 0xb8, 0xa7, 0x8d,
	0x9a, 0xaa, 0x3c, 0x91, 0x58, 0x08, 0xe3, 0xae, 0x0c, 0x86, 0x94, 0x3a, 0x94, 0xd2, 0x41, 0x20,
	0x4f, 0x2b, 0x8e, 0xf2, 0x79, 0x0a, 0xbb, 0xa5, 0xa7, 0x4a, 0x25, 0xf4, 0xc2, 0x20, 0xa0, 0x67,
	0x9b, 0x6e, 0x2c, 0x65, 0xb5, 0x4f, 0x09, 0x9d, 0xb1, 0x17, 0x88, 0xcd, 0x67, 0x3c, 0x82, 0x1d,
	0x9a, 0xab, 0x44, 0xe5, 0x12, 0x6f, 0xa8, 0x31, 0x06, 0x31, 0x10, 0x74, 0xee, 0x11, 0x36, 0x86,
	0x03, 0x8b, 0x66, 0xa9, 0x52, 0x4c, 0x84, 0x94, 0x28, 0x13, 0x29, 0xfc, 0xd0, 0xee, 0x0c, 0x9b,
	0xa3, 0x41, 0xbc, 0x5f, 0x52, 0x27, 0x9e, 0x39, 0xf5, 0x04, 0x7b, 0x01, 0x87, 0x95, 0x5e, 0x8a,
	0x95, 0x4d, 0xf4, 0x97, 0xe4, 0x1a, 0x71, 0xce, 0xfb, 0xc3, 0xe6, 0xa8, 0xbb, 0x36, 0x9c, 0x8a,
	0x95, 0xfd, 0xf4, 0xe5, 0x33, 0xe2, 0x9c, 0x8d, 0x20, 0xaa, 0x0c, 0x98, 0x87, 0xf0, 0x7c, 0x10,
	0xba, 0xaa, 0xc4, 0xdf, 0xe5, 0x14, 0x9b, 0x7d, 0xb7, 0x09, 0x8d, 0x37, 0x29, 0x16, 0xae, 0xfc,
	0x96, 0x5d, 0xfa, 0x16, 0x56, 0xa9, 0x89, 0x0a, 0x1f, 0xf3, 0x1c, 0x2a, 0x34, 0xb1, 0x4e, 0x98,
	0x60, 0xe0, 0x7b, 0x14, 0xbd, 0x7a, 0xeb, 0x85, 0x27, 0x28, 0xfe, 0x13, 0xbf, 0x3a, 0x55, 0x91,
	0xcc, 0x50, 0x48, 0xab, 0xa6, 0x39, 0x8f, 0xe8, 0xce, 0xfa, 0x1e, 0xfc, 0x50, 0x62, 0xec, 0x08,
	0x3a, 0x24, 0x52, 0x92, 0xef, 0x53, 0x9c, 0x6d, 0x7f, 0xa4, 0x2e, 0xb8, 0x57, 0x1b, 0x35, 0x91,
	0xa6, 0x68, 0xad, 0x9a, 0x64, 0xc8, 0x19, 0xb5, 0xfb, 0xe1, 0x86, 0x3c, 0x59, 0x73, 0xbe, 0xed,
	0x69, 0x3b, 0xf9, 0x70, 0x87, 0xa1, 0xed, 0xe9, 0x7c, 0x2e, 0x7d, 0xb6, 0x55, 0x83, 0x28, 0xeb,
	0x12, 0x9a, 0xb0, 0x0c, 0x25, 0xbf, 0x47, 0x4b, 0x8a, 0x95, 0xfd, 0xa1, 0xac, 0xbb, 0x2c, 0x19,
	0xf6, 0x1a, 0x1e, 0xd4, 0xbb, 0xf7, 0xb6, 0xed, 0x3e, 0xd9, 0x8e, 0x6a, 0x82, 0x5b, 0xde, 0xe7,
	0xc0, 0xbe, 0x18, 0xfc, 0xfd, 0x0a, 0xf3, 0x74, 0x45, 0x75, 0xa0, 0x5e, 0x3c, 0x0a, 0x37, 0xb5,
	0x66, 0xde, 0xe5, 0x92, 0x1a, 0xf1, 0x35, 0x3c, 0xd8, 0xa8, 0xfd, 0x75, 0xf9, 0xd5, 0x64, 0x31,
	0xd5, 0xb9, 0xb4, 0x9c, 0x93, 0xe9, 0x68, 0x2d, 0xf8, 0x10, 0xf8, 0x8b, 0x40, 0x1f, 0xff, 0xd5,
	0x84, 0x36, 0x6d, 0xf4, 0xf5, 0x26, 0x6c, 0xdc, 0xb9, 0x09, 0xb7, 0xbe, 0xde, 0x84, 0x23, 0x88,
	0xea, 0xa3, 0x46, 0xf6, 0x26, 0x89, 0x76, 0x37, 0x43, 0xf6, 0xd1, 0x07, 0xba, 0x7b, 0x28, 0x5b,
	0x77, 0x0f, 0xe5, 0x18, 0x0e, 0xea, 0xa6, 0x6b, 0x9c, 0x58, 0xe5, 0xb0, 0x1c, 0xfe, 0xfd, 0x8d,
	0xe3, 0x73, 0x20, 0x36, 0xd3, 0x93, 0xea, 0x4c, 0x1b, 0x1a, 0xf7, 0x6a, 0x7a, 0xde, 0x7a, 0xc4,
	0xa7, 0x13, 0x04, 0x12, 0x6d, 0x5a, 0x2d, 0x76, 0x42, 0x4e, 0xd1, 0xa6, 0xec, 0x19, 0xec, 0x05,
	0x3a, 0xd3, 0xf9, 0x34, 0x64, 0xd3, 0x25, 0xcd, 0x80, 0xe0, 0x9f, 0x74, 0x3e, 0xa5, 0x64, 0x46,
	0x10, 0x05, 0x9d, 0xc3, 0x1b, 0x57, 0xbe, 0xac, 0x17, 0x66, 0x84, 0xf0, 0x4b, 0xbc, 0x71, 0xe1,
	0x85, 0x1f, 0xa0, 0xbf, 0xc4, 0x99, 0x4a, 0x33, 0xa4, 0x9f, 0x11, 0x0d, 0xf4, 0xee, 0xcb, 0xa7,
	0x77, 0xff, 0x23, 0x7f, 0x0d, 0x6a, 0xff, 0x87, 0x8a, 0x77, 0x96, 0x9b, 0xc3, 0xf1, 0x19, 0xb4,
	0xe9, 0xff, 0x79, 0xab, 0x47, 0x1b, 0xb7, 0x7b, 0xf4, 0x09, 0x0c, 0x30, 0x4f, 0xb5, 0x5f, 0x0b,
	0x04, 0x51, 0xc1, 0xfa, 0x71, 0xbf, 0x04, 0xc9, 0xff, 0xd8, 0xc0, 0x4e, 0xed, 0x25, 0xac, 0x07,
	0xed, 0xf9, 0xa5, 0x11, 0x8b, 0xe8, 0x7f, 0x0c, 0x60, 0x7b, 0xfe, 0x33, 0x3a, 0xa3, 0xa3, 0x06,
	0xc1, 0xb1, 0x50, 0x59, 0xb4, 0xc5, 0xba, 0xd0, 0x9a, 0xbf, 0xb9, 0xb2, 0x51, 0x93, 0x04, 0xef,
	0xd1, 0x98, 0x55, 0xd4, 0x62, 0x03, 0xe8, 0xcd, 0xdf, 0x8a, 0x49, 0x86, 0x6f, 0x85, 0x89, 0xda,
	0xac, 0x0f, 0xdd, 0xf9, 0x99, 0xce, 0xa5, 0xce, 0x44, 0xb4, 0xcd, 0x76, 0x01, 0xe6, 0xef, 0xaf,
	0x72, 0x95, 0x5e, 0x65, 0xc2, 0x44, 0x9d, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xac, 0x80, 0x19,
	0x5b, 0x04, 0x09, 0x00, 0x00,
}
